# fly.toml app configuration file generated for ci-cd-training-phonebook on 2024-01-25T21:29:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ci-cd-training-phonebook"
primary_region = "arn"

[build]

[deploy]
  strategy = "bluegreen"

[env]
  PORT = "3000"

[processes]
  app = "node index.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
  processes = ["app"]
