# fly.toml app configuration file generated for ci-cd-training-phonebook on 2024-01-22T17:00:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ci-cd-training-phonebook"
primary_region = "arn"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[processes]
  app = "node index.js"

[[http_service.checks]]
  grace_period = "10s"
  interval = "10000"
  method = "GET"
  timeout = "5s"
  path = "/test"

[[services.script_checks]]
  command = "/app/health_check.sh"
  interval = "60s"
  restart_limit = 0
  timeout = "1s"

[deploy]
  strategy = "canary"