name: Health check

on:
  schedule:
    - cron: '0,15,30,45 * * * *'

jobs:
  check_deployment:
    runs-on: ubuntu-20.04
    steps:
      - name: Ping phone book
        uses: jtalk/url-health-check-action@v3
        with:
          # Check the following URLs one by one sequentially
          url: https://ci-cd-training-phonebook.fly.dev/health
          max-attempts: 2
          retry-delay: 5s